# Generated by Django 3.1.4 on 2020-12-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('isbn', models.CharField(max_length=30)),
                ('release_date', models.DateField(null=True)),
            ],
        ),
    ]
