# Generated by Django 3.1.4 on 2020-12-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20201207_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
